### ISSUE TITLE
Add support for HereSphere alpha channel

### ISSUE THREAD

**Issue by evilcorp9** [NodudeWasTaken/stash-hsp#1]
The augmented videos can be detected by filename postfix of: ,,_alpha", and also by stashbox tag ,,Augmented Reality"
XBVR solves this by adding following array in the json root:
"alphaPackedSettings": {
   "defaultSettings": true
}

**Comment by NodudeWasTaken** [comment]
I have added this, but i honestly dont know if anything changed.
Given that this project also has, no users, because i neither advertise nor document it, im not sure i'll ever find out

**Comment by evilcorp9** [comment]
It works surprisingly well :)
Tried it on Quest 3 HereSphere version 0.11.6.
Thank you very much!

Note: 
HereSphere likes to create local config for every played video, so if you played some video and edited some settings, the JSON attribute ,,alphaPackedSettings" cannot override local video settings. So it's best to clear those video settings in ,,Media Library" or play new videos.
